language: go
sudo: required
go:
  - 1.7.x
  - 1.9.x
  - tip
os:
  - linux
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script:
  - make
  - sudo make install
  - ciel version
  - ciel help
