language: go
sudo: required
go:
  - 1.7.6
  - 1.8.3
  - tip
os:
  - linux
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script:
  - make
  - make cross-all
  - make check
  - make install
  - ciel version
  - ciel help
