language: go
sudo: required
go:
  - 1.7.6
  - 1.8.3
  - tip
os:
  - linux
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script:
  - git submodule update --init --recursive
  - make
  - make test-cross
  - make test
  - sudo make install
  - ciel version
  - ciel help
