language: go
sudo: required
go:
  - 1.7.6
  - 1.8.3
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - make install
script:
  - make
  - make cross-all
  - make check
