#!/bin/bash
# Usage: ciel-generate <recipe>, one recipe at a time.

export CIEL_INST="__generate__"
export CIEL_BATCH_MODE="true"

# Determine architecture of build host.
BUILD_ARCH="$(dpkg-architecture -qDEB_BUILD_ARCH)"

# Determine the recipe to build.
VARIANT="$1"

# FIXME: Handy variable.
CALCULATED_RECIPE="${VARIANT^^}_RECIPE"

# Determine "small" architectures.
if [[ "${BUILD_ARCH}" != "amd64" && "${BUILD_ARCH}" != "ppc64" && \
      "${BUILD_ARCH}" != "powerpc" && "${BUILD_ARCH}" != "mips64el" && \
      "${BUILD_ARCH}" != "mipsel" ]]; then
   SMALL_ARCH=true
else
   SMALL_ARCH=false
fi

# Common denominators.
PREREQ_RECIPE="systemd"
BOOTABLE_RECIPE="boot-base kernel-base"
if "$SMALL_ARCH"; then
    FONT_RECIPE="dejavu-fonts droid-fallback-fonts freefont liberation-fonts \
                 unifont"
else
    FONT_RECIPE="noto-cjk-fonts hanazono-fonts adobe-source-code-pro \
                 adobe-source-serif-pro croscore-fonts crosextra-fonts \
                 dejavu-fonts freefont liberation-fonts roboto-fonts \
                 ttf-tibetan-machine-unicode ttf-ancient-fonts"
fi

# Define default browser.
# Firefox does not work well on PPC64.
if [[ "${BUILD_ARCH}" = "ppc64" ]]; then
	BROWSER_RECIPE="palemoon"
else
	BROWSER_RECIPE="firefox"
fi

# Available from all desktop variants.
if "$SMALL_ARCH"; then
    DESKTOP_RECIPE="${BROWSER_RECIPE} ${FONT_RECIPE} \
                    codec-base xdg-user-dirs xdg-user-dirs-gtk imchooser"
else
    DESKTOP_RECIPE="${BROWSER_RECIPE} ${FONT_RECIPE} productivity-base \
                    print-base codec-base proofread-base xdg-user-dirs \
                    xdg-user-dirs-gtk imchooser"
fi

USE_DKMS=0
# Special case for sunxi-base
if [[ "$VARIANT" = "sunxi-base" ]]; then
	if [[ ! "$DEVICE_NAME" ]]; then
		echo "DEVICE_NAME environment variable not set!" >&2
		exit 1
	fi
	case $DEVICE_NAME in
	sun[45]i*)
		BOOTABLE_RECIPE="linux+kernel+sunxi+nokvm" ;;
	sun[6789]i*)
		BOOTABLE_RECIPE="linux+kernel+sunxi+kvm" ;;
	*)
		echo "Not recognized DEVICE_NAME!" >&2
		exit 1 ;;
	esac
	BOOTABLE_RECIPE+=" u-boot-aosc-utils u-boot-$DEVICE_NAME"
	case $DEVICE_NAME in
	sun7i-a20-cubietruck|sun7i-a20-bananapi-m1-plus)
		BOOTABLE_RECIPE+=" firmware-wifi-ap6210" ;;
	sun8i-h3-bananapi-m2-plus|sun8i-r40-bananapi-m2-ultra)
		BOOTABLE_RECIPE+=" firmware-wifi-ap6212" ;;
	esac
	BOOTABLE_RECIPE+=" firmware-free firmware-nonfree"
	CALCULATED_RECIPE="BASE_RECIPE"
fi

# Special case for sunxi64-base
if [[ "$VARIANT" = "sunxi64-base" ]]; then
	if [[ ! "$DEVICE_NAME" ]]; then
		echo "DEVICE_NAME environment variable not set!" >&2
		exit 1
	fi
	BOOTABLE_RECIPE="linux+kernel+sunxi64 u-boot-aosc-utils u-boot-$DEVICE_NAME"
	case $DEVICE_NAME in
	sun50i-a64-bananapi-m64)
		BOOTABLE_RECIPE+=" firmware-wifi-ap6212" ;;
	sun50i-a64-pinebook)
		BOOTABLE_RECIPE+=" rtl8723cs"
		USE_DKMS=1 ;;
	esac
	BOOTABLE_RECIPE+=" firmware-free firmware-nonfree"
	CALCULATED_RECIPE="BASE_RECIPE"
fi
if (($USE_DKMS)); then
	BOOTABLE_RECIPE+=" gcc dkms"
fi

# Specific recipes of all variants.
CONTAINER_RECIPE="admin-base core-base editor-base python-base network-base \
                  systemd-base web-base util-base"
BASE_RECIPE="${CONTAINER_RECIPE} ${BOOTABLE_RECIPE} alsa-utils"
BUILDKIT_RECIPE="${CONTAINER_RECIPE} devel-base debug-base git autobuild3 acbs"
BUDGIE_RECIPE="${BASE_RECIPE} ${DESKTOP_RECIPE} budgie-base ibus-base gnome-distro-base \
               budgie-default-settings lightdm-gtk-greeter-settings alsa-utils"
CINNAMON_RECIPE="${BASE_RECIPE} ${DESKTOP_RECIPE} cinnamon-base cinnamon-distro-base ibus-base \
                 lightdm-gtk-greeter-settings gnome-packagekit gnome-software \
                 cinnamon-default-settings alsa-utils"
GNOME_RECIPE="${BASE_RECIPE} ${DESKTOP_RECIPE} gnome-base ibus-base gnome-distro-base \
              gnome-default-settings alsa-utils"
I3WM_RECIPE="${BASE_RECIPE} ${DESKTOP_RECIPE} i3-distro-base i3-default-settings \
             lightdm-gtk-greeter-settings arc-theme flat-remix-icon-theme \
             desktop-base alsa-utils"
KDE_RECIPE="${BASE_RECIPE} ${DESKTOP_RECIPE} kde-base fcitx-base sddm mpv kdeplasma-addons \
            alsa-utils"
LXDE_RECIPE="${BASE_RECIPE} ${DESKTOP_RECIPE} lxde-base lxde-distro-base ibus-base \
             lightdm-gtk-greeter-settings lxde-default-settings \
             arc-icon-theme network-manager-applet \
             gnome-screenshot volumeicon alsa-utils"
MATE_RECIPE="${BASE_RECIPE} ${DESKTOP_RECIPE} mate-base mate-distro-base ibus-base \
             lightdm-gtk-greeter-settings mpv mate-default-settings alsa-utils"
XFCE_RECIPE="${BASE_RECIPE} ${DESKTOP_RECIPE} xfce-base xfce-distro-base ibus-base \
             lightdm-gtk-greeter-settings mpv xfce4-default-settings alsa-utils"

# Common functions.
_recipe_post() {
	ciel factory-reset
	ciel commit
	ciel del $CIEL_INST
}

_recipe_pre_install() {
	ciel update-os
	ciel add $CIEL_INST
	ciel shell "apt -o Dpkg::Options::=\"--force-confnew\" install --yes ${PREREQ_RECIPE}"
}

# Recipe-specific functions.
_recipe_install() {
	ciel shell "apt -o Dpkg::Options::=\"--force-confnew\" install --yes ${!CALCULATED_RECIPE}"
	ciel shell "apt autoremove --purge --yes"
}
_recipe_base_config() {
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service acpid.service acpid.socket \
		apt-update.timer autovt@.service bluetooth.service  \
		fc-cache.service fcron.service fstrim.timer getty@.service \
		gpm.service lvm2-lvmetad.service lvm2-monitor.service machines.target \
		reboot.target remote-fs.target smartd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service \
		tlp-sleep.service tlp.service"
}
_recipe_sunxi-base_pre_install() {
	ciel shell "echo deb https://repo.aosc.io/os-armel/sunxi/os3-dpkg / > /etc/apt/sources.list.d/sunxi.list"
	ciel commit
	ciel shell "apt update"
}
_recipe_sunxi-base_config(){
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service \
		apt-update.timer autovt@.service bluetooth.service \
		fc-cache.service fcron.service fstrim.timer getty@.service \
		gpm.service lvm2-lvmetad.service lvm2-monitor.service machines.target \
		reboot.target remote-fs.target smartd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service"
}
_recipe_sunxi64-base_pre_install() {
	ciel shell "echo deb https://repo.aosc.io/os-arm64/sunxi/os3-dpkg / > /etc/apt/sources.list.d/sunxi64.list"
	ciel commit
	ciel shell "apt update"
}
_recipe_sunxi64-base_config(){
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service \
		apt-update.timer autovt@.service bluetooth.service \
		fc-cache.service fcron.service fstrim.timer getty@.service \
		gpm.service lvm2-lvmetad.service lvm2-monitor.service machines.target \
		reboot.target remote-fs.target smartd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service"
	if (($USE_DKMS)); then
		ciel shell "systemctl enable dkms.service"
	fi
}
_recipe_buildkit_config() {
	# FIXME: apply this to all recipes later.
	ciel shell "systemctl preset-all"
}
_recipe_budgie_config() {
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service accounts-daemon.service acpid.service \
		acpid.socket apt-update.timer autovt@.service bluetooth.service \
		fc-cache.service fcron.service fstrim.timer \
		getty@.service gpm.service lightdm.service lircd.service lvm2-lvmetad.service lvm2-monitor.service \
		machines.target org.cups.cupsd.path org.cups.cupsd.service org.cups.cupsd.socket \
		reboot.target remote-fs.target smartd.service smbd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service \
		tlp-sleep.service tlp.service udisks2.service upower.service"
}
_recipe_container_config() {
	# FIXME: apply this to all recipes later.
	ciel shell "systemctl preset-all"
}
_recipe_cinnamon_config() {
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service accounts-daemon.service acpid.service \
		acpid.socket apt-update.timer autovt@.service bluetooth.service \
		fc-cache.service fcron.service fstrim.timer \
		getty@.service gpm.service lightdm.service lircd.service lvm2-lvmetad.service lvm2-monitor.service \
		machines.target org.cups.cupsd.path org.cups.cupsd.service org.cups.cupsd.socket reboot.target \
		remote-fs.target smartd.service smbd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service \
		tlp-sleep.service tlp.service udisks2.service upower.service"
}
_recipe_gnome_config() {
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service accounts-daemon.service acpid.service \
		acpid.socket apt-update.timer autovt@.service bluetooth.service \
		fc-cache.service fcron.service fstrim.timer \
		gdm.service getty@.service gpm.service httpd.service lircd.service lvm2-lvmetad.service lvm2-monitor.service \
		machines.target org.cups.cupsd.path org.cups.cupsd.service org.cups.cupsd.socket \
		reboot.target remote-fs.target smartd.service smbd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service \
		tlp-sleep.service tlp.service udisks2.service upower.service"
}
_recipe_i3wm_config() {
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service accounts-daemon.service acpid.service \
		acpid.socket apt-update.timer autovt@.service bluetooth.service \
		fc-cache.service fcron.service fstrim.timer \
		getty@.service gpm.service lightdm.service lircd.service lvm2-lvmetad.service lvm2-monitor.service \
		machines.target org.cups.cupsd.path org.cups.cupsd.service org.cups.cupsd.socket reboot.target \
		remote-fs.target smartd.service smbd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service \
		tlp-sleep.service tlp.service udisks2.service"
}
_recipe_kde_config() {
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service accounts-daemon.service acpid.service \
		acpid.socket apt-update.timer autovt@.service bluetooth.service \
		fc-cache.service fcron.service fstrim.timer \
		getty@.service gpm.service lircd.service lvm2-lvmetad.service lvm2-monitor.service \
		machines.target org.cups.cupsd.path org.cups.cupsd.service org.cups.cupsd.socket reboot.target \
		remote-fs.target sddm.service smartd.service smbd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service \
		tlp-sleep.service tlp.service udisks2.service upower.service"
}
_recipe_lxde_config() {
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service accounts-daemon.service acpid.service \
		acpid.socket apt-update.timer autovt@.service bluetooth.service \
		fc-cache.service fcron.service fstrim.timer \
		getty@.service gpm.service lightdm.service lircd.service lvm2-lvmetad.service lvm2-monitor.service \
		machines.target org.cups.cupsd.path org.cups.cupsd.service org.cups.cupsd.socket reboot.target \
		remote-fs.target smartd.service smbd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service \
		tlp-sleep.service tlp.service udisks2.service"
}
_recipe_mate_config() {
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service accounts-daemon.service acpid.service \
		acpid.socket apt-update.timer autovt@.service bluetooth.service \
		fc-cache.service fcron.service fstrim.timer \
		getty@.service gpm.service lightdm.service lircd.service lvm2-lvmetad.service lvm2-monitor.service \
		machines.target org.cups.cupsd.path org.cups.cupsd.service org.cups.cupsd.socket reboot.target \
		remote-fs.target smartd.service smbd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service \
		tlp-sleep.service tlp.service udisks2.service upower.service"
}
_recipe_xfce_config() {
	# FIXME: preset.
	ciel shell "systemctl enable ModemManager.service NetworkManager-dispatcher.service \
		NetworkManager-wait-online.service NetworkManager.service accounts-daemon.service acpid.service \
		acpid.socket apt-update.timer autovt@.service bluetooth.service \
		fc-cache.service fcron.service fstrim.timer \
		getty@.service gpm.service lightdm.service lircd.service lvm2-lvmetad.service lvm2-monitor.service \
		machines.target org.cups.cupsd.path org.cups.cupsd.service org.cups.cupsd.socket reboot.target \
		remote-fs.target smartd.service smbd.service sshd.service systemd-networkd-wait-online.service \
		systemd-networkd.service systemd-networkd.socket systemd-resolved.service systemd-timesyncd.service \
		tlp-sleep.service tlp.service udisks2.service upower.service"
}

# Nike.
set -e
_recipe_pre_install
if type _recipe_${1}_pre_install >/dev/null 2>&1; then
	_recipe_${1}_pre_install
fi
_recipe_install
_recipe_${1}_config
_recipe_post
set +e
