#!/bin/bash
# Usage: ciel-release <variant>, where <variant> is the name of the variant.
#        This command will also invoke ciel-generate, so <variant> should be one of
#        which defined in ciel-generate.
XZ_PARAM="-9 -e --lzma2=preset=9e,nice=273"
DATE="$(TZ=UTC date +'%Y%m%d')"
ARCH="$(dpkg-architecture -qDEB_BUILD_ARCH)"
VARIANT="$1"

if [[ ! "$CIEL_INSTANCE" ]]; then
	echo "Please specify an instance via environment variable first."
	echo "CIEL_INSTANCE=..."
	exit 127
fi

if [[ ! "$TARBALL" ]]; then
	TARBALL=aosc-os_${VARIANT}_"${DATE}"_"${ARCH}".tar.xz
fi

pushd "$CIEL_INSTANCE" || exit $?

_ciel_tarball() {
	# Make a tarball
	tar cvf - * | $COMPRESSOR > ../"$TARBALL" || exit $?
	# Generate SHA256 checksum.
	sha256sum ../"$TARBALL" > ../"$TARBALL".sha256sum || exit $?
}

if [[ ! "$COMPRESSOR" ]]; then
	if [ -z "$2" ]; then
		echo "Usage: ciel release <variant> <threads>"
		echo ""
		echo "<threads> not defined or not a natural integer!"
		echo "Defaulting to 0, using as many threads as possible!"
		echo "This could result in out-of-memory conditions"
		echo ""
		echo "Please declare a natural integer for XZ thread count."
		echo "The higher the thread count, the higher the memory requirement."
		export XZ_THREADS=0
	else
		export XZ_THREADS=$2
	fi
	COMPRESSOR="xz $XZ_PARAM -T $XZ_THREADS"
fi

_ciel_tarball

popd
