#!/bin/bash
set -e

ciel shell "apt update --yes"
ciel shell "apt -o Dpkg::Options::=\"--force-confnew\" full-upgrade --yes"
ciel shell "apt autoremove --purge --yes"

#ciel merge-cache
#ciel clean --factory-reset
#ciel merge dist /

set +e
