#!/bin/bash

# Strict mode, assuming Autobuild3 and ACBS catches errors properly.
set -e
ciel shell "acbs-build $1"
# And turn it off.
set +e

if ls "$CIEL_INST"/os-* 1> /dev/null 2>&1; then
	cp -rpv "$CIEL_INST"/os-* ./
fi
if [[ -e "$CIEL_INST"/var/log/apt/history.log ]]; then
	cp -pv "$CIEL_INST"/var/log/apt/history.log ./
fi

# Merge cache, namely APT packages and catalogues.
ciel merge-cache
ciel clean
