#!/bin/bash
set -e
ciel ~update
ciel shell "apt -o Dpkg::Options::=\"--force-confdef\" -o Dpkg::Options::=\"--force-confnew\" install --yes systemd"
ciel shell "apt -o Dpkg::Options::=\"--force-confdef\" -o Dpkg::Options::=\"--force-confnew\" install --yes admin-base core-base editor-base python-base network-base systemd-base web-base util-base devel-base debug-base git autobuild3 acbs"
ciel shell "systemctl preset-all"
ciel shell "apt autoremove --purge --yes"
ciel merge-cache
ciel clean --factory-reset
ciel merge dist /
set +e
