#!/bin/bash
MOUNT_POINT="$(ciel mount $*)"
WORKDIR="$PWD"
cd "$MOUNT_POINT"
tar cvf - *  | xz -T 0 -9 -e --lzma2=preset=9e,nice=273 > "$WORKDIR"/stub-shizitou.tar.xz
cd "$WORKDIR"
umount "$MOUNT_POINT"
rmdir "$MOUNT_POINT"
